### ISSUE TITLE
Abandoned? Or just taking a rest...

### ISSUE THREAD

**Issue by croxton** [workingconcept/lever-craft-plugin#5]
Is this plugin still supported? The reason I ask is it's marked as abandoned in the Craft Plugin Store, yet the recently added support for Craft 4 implies it just might have a future?

**Comment by mattstein** [comment]
Officially no, I don’t plan on spending any more time with it. I updated it with Craft 4 support because someone (other than me) was [almost using it](https://github.com/workingconcept/lever-craft-plugin/issues/4)—so it’s relatively safe to use despite a murky future. Anyone’s welcome to run with it or replace it, though!
